version: "3.6"

services:

  user_manager_db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      # this is only for development purpose
      - "5343:5343"
    env_file:
      - env_file
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "db", "-d", "user_manager_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  user_manager_ms:
    # Building the image
    <<: &user_manager_ms
      image: "user-manager:latest"
      build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "10002:10002"
    env_file: 
      - env_file
    environment:
      - POSTGRES_HOST=user_manager_db
    depends_on:
      - user_manager_db
      - user_ms_migrations

  user_ms_migrations:
    <<: *user-manager
    command: sh -c "flask db init && flask db migrate && flask db upgrade" 
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=user_manager_db
    depends_on:
      user_manager_db:
        condition: service_healthy

volumes:
  data: